displayName=Debug Helper
author=Abex
support=https://runelite.net/discord
description=Lets a dev debug various issues
tags=debug,profile
plugins=abex.os.debug.DebugPlugin
build=you set the wrong commit, this branch does not deploy to the plugin-hub