on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  linux-amd64:
    runs-on: ubuntu-20.04
    container:
      image: amd64/centos:7.9.2009
    steps:
    - name: install dependencies
      run: |
        set -e -x
        curl -Lo cmake-3.23.2-linux-x86_64.tar.gz 'https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz'
        echo "aaced6f745b86ce853661a595bdac6c5314a60f8181b6912a0a4920acfa32708  cmake-3.23.2-linux-x86_64.tar.gz" | sha256sum -c
        tar -xf cmake-3.23.2-linux-x86_64.tar.gz
        mv cmake-3.23.2-linux-x86_64 cmake
        yum -y install git java-11-openjdk-devel "@Development Tools"
    - name: build linux-amd64
      run: |
        set -e -x
        git clone --recursive https://github.com/abextm/runelite-debug-plugin.git
        mkdir -p build/linux-amd64
        cd build/linux-amd64
        ../../cmake/bin/cmake -S ../../runelite-debug-plugin/native -B .
        make Profiler -j2
    - uses: actions/upload-artifact@v3
      with:
        name: linux-amd64
        path: build/linux-amd64/libProfiler.so
        retention-days: 1
        if-no-files-found: error
  macos-universal:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build macos-universal
      run: |
        set -e -x
        mkdir -p build/macos-universal
        cd build/macos-universal
        cmake -S ../../native -B .
        make Profiler -j2
    - uses: actions/upload-artifact@v3
      with:
        name: macos-universal
        path: build/macos-universal/libProfiler.dylib
        retention-days: 1
        if-no-files-found: error
  windows-amd64:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        toolset: 14.0
    - name: build windows-amd64
      run: |
        mkdir -p build/windows-amd64
        cd build/windows-amd64
        cmake -S ../../native -B . -G Ninja
        if (!$?) { exit 1 }
        ninja Profiler
        if (!$?) { exit 1 }
    - uses: actions/upload-artifact@v3
      with:
        name: windows-amd64
        path: build/windows-amd64/profiler.dll
        retention-days: 1
        if-no-files-found: error
  windows-x86:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
        toolset: 14.0
    - name: build windows-x86
      run: |
        mkdir -p build/windows-x86
        cd build/windows-x86
        cmake -S ../../native -B . -G Ninja
        if (!$?) { exit 1 }
        ninja Profiler
        if (!$?) { exit 1 }
    - uses: actions/upload-artifact@v3
      with:
        name: windows-x86
        path: build/windows-x86/profiler.dll
        retention-days: 1
        if-no-files-found: error
  java:
    runs-on: ubuntu-20.04
    needs: [linux-amd64, macos-universal, windows-amd64, windows-x86]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
    - uses: actions/download-artifact@v3
      with:
        path: src/main/resources/natives
    - name: bump
      if: ${{ github.event.inputs.RELEASE == 'yes' }}
      run: perl -i -p -e 's/-SNAPSHOT$//' version
    - name: build
      run: |
        set -e -x
        touch src/main/resources/natives/cibuilt
        ./gradlew test
    - name: commit
      run: |
        set -e -x
        COMMIT="$(git rev-parse HEAD)"
        git checkout -b binaries-$COMMIT
        git config user.name "Release Script"
        git config user.email abex@runelite.net
        git add src/main/resources/natives/**
        git add version
        git commit -m "Binaries for $COMMIT"
        git show HEAD
        git push origin binaries-$COMMIT